-- Create 'news' table for Hybrid Intelligence
create table if not exists news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Data
  team_name text not null,
  title text not null,
  summary text,
  url text,
  source text not null, -- e.g. 'Football Italia', 'Sky Sports'
  published_at timestamp with time zone not null,
  
  -- Engine Data
  category text not null, -- 'injury', 'suspension', 'coach_change', 'form', 'motivation', 'other'
  sentiment numeric not null default 0, -- Range: -1.0 to 1.0
  reliability numeric not null default 1.0, -- Range: 0.0 to 1.0
  
  -- JSON details (optional extra data)
  metadata jsonb default '{}'::jsonb
);

-- Enable Row Level Security
alter table news enable row level security;

-- Policies
-- 1. Everyone can READ news (Frontend needs this)
create policy "Allow public read news"
  on news for select
  to anon
  using (true);

-- 2. Only Admins/Service Role can INSERT/UPDATE/DELETE
create policy "Admins can manage news"
  on news for all
  using ( public.is_admin() );

-- Index for fast lookup by team
create index if not exists idx_news_team_name on news(team_name);
create index if not exists idx_news_published_at on news(published_at desc);
