-- Table to store historical match data (bulk uploaded via CSV)
create table if not exists matches (
  id bigint generated by default as identity primary key,
  date date not null,
  home_team text not null,
  away_team text not null,
  home_goals integer not null,
  away_goals integer not null,
  home_xg numeric default 0, -- optional if CSV has xG
  away_xg numeric default 0,
  season text, -- e.g. "2024-2025"
  league text -- e.g. "Premier League"
);

-- Enable RLS
alter table matches enable row level security;

-- Policies
-- Public can READ matches (to calculate stats)
create policy "Allow public read matches"
  on matches for select
  to anon
  using (true);

-- Only ADMINS can INSERT/UPDATE/DELETE matches
-- (We use the is_admin() function created in rbac_schema.sql)
create policy "Admins can manage matches"
  on matches for all
  using ( public.is_admin() );
