-- Create a table to store prediction results
create table if not exists predictions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  home_team text not null,
  away_team text not null,
  home_xg numeric not null,
  away_xg numeric not null,
  prob_home numeric not null, -- stored as 0.45 for 45%
  prob_draw numeric not null,
  prob_away numeric not null,
  predicted_outcome text -- e.g. "HOME_WIN" based on highest prob
);

-- Turn on Row Level Security (good practice)
alter table predictions enable row level security;

-- Allow anyone (anon) to insert predictions (since it's a public demo app)
create policy "Allow public inserts"
on predictions for insert
to anon
with check (true);

-- Allow anyone to read predictions
create policy "Allow public read"
on predictions for select
to anon
using (true);
